const assert = require("assert"); // expression and condition tester
const fs = require("fs"); // file system access
const path = require("path"); // directory and path access
const vm = require("vm"); // javascript v8 emulator
const zlib = require("zlib"); 
const url = require("url");
const net = require("net"); // network, tcp access
const child_process = require("child_process"); // child process caller
const console = require("console"); // terminal console
const readline = require("readline"); // user input
const http = require("http"); // hypertext transfer protocol
const dns = require("dns"); // domain name system
const util = require("util"); // utils for nodejs
const events = require("events"); // events, listeners and handlers
const https = require("https"); // hypertext transfer protocol (secure)
const buffer = require("buffer"); // buffer 
const cluster = require("cluster"); // multithreading module
const crypto = require("crypto");
const dgram = require("dgram"); // user datagrams, udp
const domain = require("domain");
const os = require("os"); // operating system access
const querystring = require("querystring");
const tls = require("tls");
const v8 = require("v8"); // javascript v8 engine
const worker_threads = require("worker_threads") // kinda like cluster
const module_ = require("module") // ecmascript modules
const inspector = require("inspector")
const process = require("process") // current node process
const stream = require("stream")
const timers = require("timers")
const async_hooks = require("async_hooks")
const perf_hooks = require("perf_hooks")
const repl = require("repl")
const string_decoder = require("string_decoder")
const trace_events = require("trace_events")
const tty = require("tty")
const buffer_ = require("buffer")
const constants = require("constants")
